fix/victor connection banner
codersforcauses/FoGUWA pull request #31
Opened 2019-12-28 04:25 UTC by VicJohn447

using a snackbar to display connection message instead of an alert

2019-12-28 05:56 UTC, JeremiahPinto commented on layouts/default.vue
> +          v-model="$nuxt.isOffline"
This removes the previous trigger which lets the user know if they can't use geolocation. You will have to add the `$nuxt.isOffline` to the computed property as was previously done.

2019-12-28 05:58 UTC, JeremiahPinto requested changes
Please fix the issue I have outlined next to the code. I know that the code that uses it is commented out for now, but it will be used when we have the backend running

2019-12-31 07:16 UTC, JeremiahPinto commented on layouts/default.vue
> +          :color="snackbarColour"
Doesn't need a dynamic colour if this never changes

2019-12-31 07:17 UTC, JeremiahPinto commented on layouts/default.vue
> +          {{ offlineText }}
Don't need a variable for static text

2020-01-03 03:06 UTC, JeremiahPinto reviewed
Why is the entire file marked as changed? Maybe check your line endings (Should be `LF`).

2020-01-03 15:38 UTC, Drewbi commented
This PR Is disconnected from the branch for some reason. Use the other one to merge.

2020-01-03 15:38 UTC, closed without merging